### ISSUE TITLE
Menu should show on by default. 

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#35]
Can we show the header and footer menu by default?

**Comment by lunule** [comment]
No. :) That's because there's no such thing as default menu.
When the user installs the theme, in a lot of cases the user still doesn't have any menu configured.

So, the following cases are defined:
1. Theme is installed and there's no menu to display - in this case a 'Home' link is displayed in the header and footer menu containers;
2. There are menus available, but none of them are selected as Header or Footer Menu in the appropriate customizer sections. In this case the first created menu is displayed both in the header and footer menu containers;
3. There are menus available and the necessary assignments are done in the appropriate customizer sections. In this case the displayed menu is the one that has been assigned in the backend.

As this is another development chapter with myriads of variations, and it can happen ever after hours of testing that I miss some tricky case, I rather keep this issue open for a few days - I'm looking forward to reading the results of your tests.

**Comment by lunule** [comment]
I close this - please reopen if you have any further issues/requests concerning the default menu display.
