### ISSUE TITLE
Header Color

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#37]
Header text color doesn't do anything.  The link color still changes the link color of the buttons.

**Comment by lunule** [comment]
Header text color - it really doesn't, that's because there's no unlinked text in the header, only links. In fact this text color control could be completely removed, as everything the header might have is linked: the site name ( when no logo image is configured ), the menu items, the buttons. Currently the only not-linked element can be the search field in the right side content. But it also has a gray placeholder text which has a predefined light gray color which can be changed only with some painful code updates.

So, what do you think? Should I remove it, or let's see those painful code updates?

( Button color issue - I fixed that. )

**Comment by Conutant** [comment]
Ok, I think I would like to keep it because you can just add in regular text like call me: 310 888-9999 and it will show up in that color.  What do you think?

**Comment by Conutant** [comment]
Also maybe we can make it so regular text is able to change colors and is centered in the middle of the menu.

**Comment by lunule** [comment]
_Ok, I think I would like to keep it because you can just add in regular text like call me: 310 888-9999 and it will show up in that color. What do you think?_

Agree. :) 

_Also maybe we can make it so regular text is able to change colors and is centered in the middle of the menu._

I'm not sure I understand this. What type of color change do you mean besides the user's ability to change the text color using the appropriate Customizer setting?

Concerning centering in the middle of the menu: I'm afraid this can not be done in a generalized way. At least as far as I see, if you don't know how many menu items the user displays, and how long the menu items are, you can not know for sure if a centered content will not overlap the some menu item.
The most simple example: in case of a menu containing 6 items you can create a menu in which three items are positioned to the left, another three to the right of the centered content. 
BUT once the user adds a seventh menu item, the whole structure gets broken, because the fourth menu item will be a central menu item, thus overlapping the central content or overlapped by it.

I'm looking forward to reading your thoughts about this.

**Comment by Conutant** [comment]
Oh I just meant that the color changer was not working on the regular text.  Also for the centered positioning, sorry about that.  I meant centered vertically not horizontally.

**Comment by lunule** [comment]
Fixed (- both the vertical centering and the text color related issue)
